# Generated by Django 4.0.6 on 2022-09-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetails',
            name='blog_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
