# Generated by Django 4.0.6 on 2022-09-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogdetails_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetails',
            name='blog_text',
            field=models.TextField(),
        ),
    ]
